describe('Check the Payment Functionality', () => {
    const emailQris = 'testingfauzi456@gmail.com'
    const passwordQris = 'fauzi123'
    const emailTf = 'testingfauzi789@gmail.com'
    const passwordTf = 'fauzi123'
    it('Payment with QRIS without upload Foto Bukti Pembayaran', () => {
        cy.viewport(1280, 720)
        cy.visit('http://127.0.0.1:8000/')
        cy.get('.container > .btn-book-a-table').click()
        cy.get('#email').type(emailQris)
        cy.get('#password').type(passwordQris)
        cy.get('#signin').click()
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('.col-2 > .btn').contains('Bayar Sekarang').click()
        cy.get(':nth-child(1) > .nav-link > h4').click({ force: true })
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('#payment-button').click()
        cy.wait(2000)
    })

    it('Payment with QRIS & upload Foto Bukti Pembayaran', () => {
        cy.viewport(1280, 720)
        cy.visit('http://127.0.0.1:8000/')
        cy.get('.container > .btn-book-a-table').click()
        cy.get('#email').type(emailQris)
        cy.get('#password').type(passwordQris)
        cy.get('#signin').click()
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('.col-2 > .btn').contains('Bayar Sekarang').click()
        cy.get(':nth-child(1) > .nav-link > h4').click({ force: true })
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('#fileToUpload').selectFile('cypress/fixtures/bukti.jpeg')
        cy.wait(2000)
        cy.get('#payment-button').click({ force: true })
        cy.get(':nth-child(4) > a').click()
        cy.scrollTo(0, 500)
        cy.get('h3').contains('Status : Menunggu Konfirmasi Admin')
        cy.wait(2000)
    })

    it('Payment with Transfer without upload Foto Bukti Pembayaran', () => {
        cy.viewport(1280, 720)
        cy.visit('http://127.0.0.1:8000/')
        cy.get('.container > .btn-book-a-table').click()
        cy.get('#email').type(emailTf)
        cy.get('#password').type(passwordTf)
        cy.get('#signin').click()
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('.col-2 > .btn').contains('Bayar Sekarang').click()
        cy.get(':nth-child(2) > .nav-link > h4').click({ force: true })
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('#payment-button').click({ force: true })
        cy.wait(2000)
    })

    it('Payment with Transfer & upload Foto Bukti Pembayaran', () => {
        cy.viewport(1280, 720)
        cy.visit('http://127.0.0.1:8000/')
        cy.get('.container > .btn-book-a-table').click()
        cy.get('#email').type(emailTf)
        cy.get('#password').type(passwordTf)
        cy.get('#signin').click()
        cy.wait(2000)
        cy.get('ul > :nth-child(4) > a').click()
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('.col-2 > .btn').contains('Bayar Sekarang').click()
        cy.get(':nth-child(2) > .nav-link > h4').click({ force: true })
        cy.scrollTo(0, 500)
        cy.wait(2000)
        cy.get('#fileToUpload').selectFile('cypress/fixtures/bukti.jpeg', { force: true })
        cy.wait(2000)
        cy.get('#payment-button').click({ force: true })
        cy.get(':nth-child(4) > a').click({ force: true })
        cy.scrollTo(0, 500)
        cy.get('h3').contains('Status : Menunggu Konfirmasi Admin')
        cy.wait(2000)
    })
})